CREATE TABLE "REPORTDATA_OWNER"."LU_GRUP_SPECIE"
 ("OID" NUMBER(*,0),
  "CODE" NVARCHAR2(255),
  "DESCRIPTION" NVARCHAR2(255)
 );

Insert into REPORTDATA_OWNER.LU_GRUP_SPECIE (OID,CODE,DESCRIPTION) values (1,'A','Amfibieni');
Insert into REPORTDATA_OWNER.LU_GRUP_SPECIE (OID,CODE,DESCRIPTION) values (2,'F','Pesti');
Insert into REPORTDATA_OWNER.LU_GRUP_SPECIE (OID,CODE,DESCRIPTION) values (3,'M','Mamifere');
Insert into REPORTDATA_OWNER.LU_GRUP_SPECIE (OID,CODE,DESCRIPTION) values (4,'P','Plante');
Insert into REPORTDATA_OWNER.LU_GRUP_SPECIE (OID,CODE,DESCRIPTION) values (5,'R','Reptile');
Insert into REPORTDATA_OWNER.LU_GRUP_SPECIE (OID,CODE,DESCRIPTION) values (6,'I','Nevertebrate');

ALTER TABLE "REPORTDATA_OWNER"."LU_GRUP_SPECIE" MODIFY ("OID" NOT NULL ENABLE);
