ALTER TABLE "REPORTDATA_OWNER"."LU_BIOGEOREG" ADD "NUME" NVARCHAR2(50);
Update REPORTDATA_OWNER.LU_BIOGEOREG SET NUME = 'Alpin' WHERE OBJECTID = 1;
Update REPORTDATA_OWNER.LU_BIOGEOREG SET NUME = 'Marea Neagra' WHERE OBJECTID = 3;
Update REPORTDATA_OWNER.LU_BIOGEOREG SET NUME = 'Continental' WHERE OBJECTID = 5;
Update REPORTDATA_OWNER.LU_BIOGEOREG SET NUME = 'Regiunea marină a Mării Negre' WHERE OBJECTID = 9;
Update REPORTDATA_OWNER.LU_BIOGEOREG SET NUME = 'Panonic' WHERE OBJECTID = 13;
Update REPORTDATA_OWNER.LU_BIOGEOREG SET NUME = 'Stepic' WHERE OBJECTID = 14;
