# encoding: utf-8

revision = '2f0625b248bc'
down_revision = '236f754feafc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


def upgrade():
    op.add_column('lu_threats',
        sa.Column('name_ro', sa.UnicodeText, nullable=True))

    lu_threats_codes = table('lu_threats',
        column('code', sa.String),
        column('name_ro', sa.UnicodeText))

    for code, name_ro in DATA:
        op.execute(
            lu_threats_codes.update()
                .where(lu_threats_codes.c.code == op.inline_literal(code))
                .values({'name_ro': op.inline_literal(name_ro)}))


def downgrade():
    op.drop_column('lu_threats', 'name_ro')


DATA = [
    ("A", u"Agricultură"),
    ("A01", u"Cultivare"),
    ("A02", u"Modificarea practicilor de cultivare"),
    ("A02.01", u"Agricultură intensivă"),
    ("A02.02", u"Schimbarea culturii"),
    ("A02.03", u"Inlocuirea pășunii cu terenuri arabile"),
    ("A03", u"Cosire/Tăiere a pășunii"),
    ("A03.01", u"Cosire intensivă sau intensificarea cosirii"),
    ("A03.02", u"Cosire ne-intensivă"),
    ("A03.03", u"Abandonarea/lipsa cosirii"),
    ("A04", u"Pășunatul"),
    ("A04.01", u"Pășunatul intensiv"),
    ("A04.01.01", u"Pășunatul intensiv al vacilor"),
    ("A04.01.02", u"Pășunatul intensiv al oilor"),
    ("A04.01.03", u"Pășunatul intensiv al cailor"),
    ("A04.01.04", u"Pășunatul intensiv al caprelor"),
    ("A04.01.05", u"Pășunatul intensiv în amestec de animale"),
    ("A04.02", u"Pășunatul neintensiv"),
    ("A04.02.01", u"Pășunatul ne-intensiv al vacilor"),
    ("A04.02.02", u"Pășunatul ne-intensiv al oilor"),
    ("A04.02.03", u"Pășunatul ne-intensiv al cailor"),
    ("A04.02.04", u"Pășunatul ne-intensiv al caprelor"),
    ("A04.02.05", u"Pășunatul ne-intensiv în amestec de animale"),
    ("A04.03", u"Abandonarea sistemelor pastorale, lipsa pășunatului"),
    ("A05", u"Creșterea animalelor (fără pășunat)"),
    ("A05.01", u"Creșterea animalelor"),
    ("A05.02", u"Furajare"),
    ("A05.03", u"Lipsa creșterii animalelor"),
    ("A06", u"Culturi anuale și perene nelemnoase"),
    ("A06.01", u"Culturi anuale pentru producția de alimente"),
    ("A06.01.01", u"Culturi anuale intensive pentru producția de alimente/(intensificarea culturilor anuale pentru producția de alimente"),
    ("A06.01.02", u"Culturi anuale ne-intensive pentru producția de alimente"),
    ("A06.02", u"Culturi perene nelemnoase"),
    ("A06.02.01", u"Culturi perene nelemnoase intensive/intensificarea culturilor (perene nelemnoase"),
    ("A06.02.02", u"Culturi perene nelemnoase neintensive"),
    ("A06.03", u"Producție de biocombustibili"),
    ("A06.04", u"Abandonarea culturii pentru producție"),
    ("A07", u"Utilizarea produselor biocide, hormoni si substanțe chimice"),
    ("A08", u"Fertilizarea (cu îngrășămant)"),
    ("A09", u"Irigarea"),
    ("A10", u"Restructurarea deținerii terenului agricol"),
    ("A10.01", u"Îndepărtarea gardurilor vii și a crângurilor sau tufișurilor"),
    ("A10.02", u"Îndepărtarea zidurilor din piatră și a digurilor"),
    ("A11", u"Alte activități agricole decât cele listate mai sus"),
    ("B", u"Silvicultură"),
    ("B01", u"Plantarea de pădure pe teren deschis"),
    ("B01.01", u"Plantare pădure, pe teren deschis (copaci nativi)"),
    ("B01.02", u"Plantare artificială, pe teren deschis (copaci nenativi)"),
    ("B02", u"Gestionarea și utilizarea pădurii și plantației"),
    ("B02.01", u"Replantarea pădurii"),
    ("B02.01.01", u"Replantarea pădurii (copaci nativi)"),
    ("B02.01.02", u"Replantarea pădurii (copaci nenativi)"),
    ("B02.02", u"Curățarea pădurii"),
    ("B02.03", u"Indepărtarea lăstărișului"),
    ("B02.04", u"Indepărtarea arborilor uscați sau în curs de uscare"),
    ("B02.05", u"Producția lemnoasă ne-intensivă (lăsarea lemnului mort/neatingerea (de copacii vechi)"),
    ("B02.06", u"Decojirea scoarței copacului"),
    ("B03", u"Exploatare forestieră fără replantare sau refacere naturală"),
    ("B04", u"Folosirea biocidelor, hormonilor și chimicalelor (în pădure)"),
    ("B05", u"Folosirea de ingrășăminte (în pădure)"),
    ("B06", u"Pășunatul în pădure/în zona împădurită"),
    ("B07", u"Alte activități silvice decât cele listate mai sus"),
    ("C", u"Minerit, extracția de materiale și de producție de energie"),
    ("C01", u"Industria extractivă"),
    ("C01.01", u"Extragere de nisip și pietriș"),
    ("C01.01.01", u"Cariere de nisip și pietriș"),
    ("C01.01.02", u"Scoaterea de material de pe plaje"),
    ("C01.02", u"Puțuri de argilă (lut) și chirpici"),
    ("C01.03", u"Extracția de turbă"),
    ("C01.03.01", u"Extragerea manuală a turbei"),
    ("C01.03.02", u"Extragerea mecanizat a turbei"),
    ("C01.04", u"Mine"),
    ("C01.04.01", u"Minerit de suprafață"),
    ("C01.04.02", u"Minerit subteran"),
    ("C01.05", u"Saline"),
    ("C01.05.01", u"Saline abandonate"),
    ("C01.05.02", u"Saline modificate"),
    ("C01.06", u"Prospecțiuni geotehnice"),
    ("C01.07", u"Minerit și activități de extragere la care nu se referă mai sus"),
    ("C02", u"Exploatarea și extracția de petrol și gaze"),
    ("C02.01", u"Foraj de explorare"),
    ("C02.02", u"Foraj de producție"),
    ("C02.03", u"Instalații de foraj"),
    ("C02.04", u"Instalații semi-submersibile"),
    ("C02.05", u"Foraj cu ajutorul navelor speciale pentru foraj"),
    ("C03", u"Utilizarea energiei din surse regenerabile abiotice"),
    ("C03.01", u"Geotermală"),
    ("C03.02", u"Solară"),
    ("C03.03", u"Eoliană"),
    ("C03.04", u"Maree"),
    ("D", u"Rețele de comunicații"),
    ("D01", u"Drumuri, poteci și căi ferate"),
    ("D01.01", u"Poteci,trasee,trasee pentru ciclism"),
    ("D01.02", u"Drumuri, autostrăzi"),
    ("D01.03", u"Parcuri auto și parcări"),
    ("D01.04", u"Căi ferate, căi ferate de mare viteză"),
    ("D01.05", u"Poduri, viaducte"),
    ("D01.06", u"Tunele"),
    ("D02", u"Linii de utilități și servicii"),
    ("D02.01", u"Linii electrice și de telefonie"),
    ("D02.01.01", u"Linii electrice și de telefon suspendate"),
    ("D02.01.02", u"Linii electrice și de telefon subterane/scufundate"),
    ("D02.02", u"Conducte"),
    ("D02.03", u"Piloni și antene de comunicare"),
    ("D02.09", u"Alte forme de transport de energie"),
    ("D03", u"Rute navale, porturi, construcții marine"),
    ("D03.01", u"Zonă portuară"),
    ("D03.01.01", u"Rampe"),
    ("D03.01.02", u"Diguri/zone turistice și de agrement"),
    ("D03.01.03", u"Zonă de pescuit"),
    ("D03.01.04", u"Zonă industrial portuară"),
    ("D03.02", u"Navigație"),
    ("D03.02.01", u"Benzi de marfă"),
    ("D03.02.02", u"Benzi de transport de pasageri (de mare viteză)"),
    ("D03.03", u"Construcții marine"),
    ("D04", u"Aeroporturi, rute de zbor"),
    ("D04.01", u"Aeroport"),
    ("D04.02", u"Aerodrom, helioport"),
    ("D04.03", u"Rute de zbor"),
    ("D05", u"Îmbunătățirea accesului in zonă"),
    ("D06", u"Alte forme de transport și comunicație"),
    ("E", u"Urbanizare, dezvoltare rezidențială și comercială"),
    ("E01", u"Zone urbanizate, habitare umană (locuințe umane)"),
    ("E01.01", u"Urbanizare continuă"),
    ("E01.02", u"Urbanizare discontinuă"),
    ("E01.03", u"Habitare dispersată (locuințe risipite, disperse)"),
    ("E01.04", u"Alte modele(tipuri) de habitare/locuințe"),
    ("E02", u"Zone industriale sau comerciale"),
    ("E02.01", u"Fabrici"),
    ("E02.02", u"Depozite industriale"),
    ("E02.03", u"Alte zone industriale/comerciale"),
    ("E03", u"Descărcări"),
    ("E03.01", u"Depozitarea deșeurilor menajere /deșeuri provenite din baze de (agrement"),
    ("E03.02", u"Depozitarea deșeurilor industriale"),
    ("E03.03", u"Depozitarea materialelor inerte(nereactive)"),
    ("E03.04", u"Alte tipuri de depozitări"),
    ("E03.04.01", u"Depuneri costiere de nisip/creșterea plajelor"),
    ("E04", u"Infrastructuri, construcții în peisaj"),
    ("E04.01", u"Infrastructuri agricole, construcții în peisaj"),
    ("E04.02", u"Baze și construcții militare în peisaj"),
    ("E05", u"Depozite de materiale"),
    ("E06", u"Alte activități de urbanizare și industriale similare"),
    ("E06.01", u"Demolarea de clădiri și structuri umane"),
    ("E06.02", u"Reconstrucția, renovarea clădirilor"),
    ("F", u"Folosirea resurselor biologice, altele decat agricultură și (silvicultură"),
    ("F01", u"Acvacultură marină și de apă dulce"),
    ("F01.01", u"Piscicultură intensivă, intensificată"),
    ("F01.02", u"Culturi suspendate"),
    ("F01.03", u"Culturi bentonice"),
    ("F02", u"Pescuit și recoltarea resurselor acvatice"),
    ("F02.01", u"Pescuit profesional pasiv"),
    ("F02.01.01", u"Cu capcane, vârse, vintire etc."),
    ("F02.01.02", u"Cu plasă"),
    ("F02.01.03", u"Cu paragate, în zona litorală"),
    ("F02.01.04", u"Cu paragate, în zona pelagică"),
    ("F02.02", u"Pescuit profesional activ"),
    ("F02.02.01", u"Traule în zona bentonică sau litorală"),
    ("F02.02.02", u"Traule în zona pelagică"),
    ("F02.02.03", u"Pescuit de adancime într-o locație fixă (pescuit cu setcă / (avă, în zona litorală)"),
    ("F02.02.04", u"Pescuit pelagic într-o locație fixă (pescuit cu setcă/plasă-(pungă, în zonă pelagică)"),
    ("F02.02.05", u"Dragare bentonică"),
    ("F02.03", u"Pescuit de agrement"),
    ("F02.03.01", u"Săpat după momeală / colectare"),
    ("F02.03.02", u"Pescuit cu undiță"),
    ("F02.03.03", u"Pescuit cu ostia"),
    ("F03", u"Vânătoarea și colectarea animalelor sălbatice (terestre)"),
    ("F03.01", u"Vânătoare"),
    ("F03.01.01", u"Prejudicii cauzate prin vânătoare (densitatea populațională în (exces)"),
    ("F03.02", u"Luare / prelevare de faună(terestră)"),
    ("F03.02.01", u"Colectare de animale (insecte, reptile, amfibieni...)"),
    ("F03.02.02", u"Luare din cuib (Falconidaei)"),
    ("F03.02.03", u"Capcane, otrăvire, braconaj"),
    ("F03.02.04", u"Controlul prădătorilor"),
    ("F03.02.05", u"Captura accidentală"),
    ("F03.02.09", u"Alte forme de luare(extragere) faună"),
    ("F04", u"Luare/prelevare de plante terestre, în general"),
    ("F04.01", u"Prădarea stațiunilor floristice(rezervațiiile floristice)"),
    ("F04.02", u"Colectarea (ciuperci, licheni, fructe de pădure etc)"),
    ("F04.02.01", u"Adunare manuală"),
    ("F04.02.02", u"Colectare manuală"),
    ("F05", u"Luare ilegală/prelevare de faună marină"),
    ("F05.01", u"Dinamită"),
    ("F05.02", u"Pescuit de scoici Lithophaga (nu traiesc in Marea Neagra!!)"),
    ("F05.03", u"Pescuit prin otrăvire"),
    ("F05.04", u"Braconaj"),
    ("F05.05", u"Vanatoare cu arma"),
    ("F05.06", u"Luarea în scop de colecționare"),
    ("F05.07", u"Altele (ex. cu plase derivante)"),
    ("F06", u"Alte activități de vânătoare, pescuit sau colectare decât cele de mai (sus"),
    ("F06.01", u"Stații de creștere a păsărilor/vânatului(în general)"),
    ("G", u"Intruziuni și dezechilibre umane"),
    ("G01", u"Sport în aer liber și activități de petrecere a timpului liber, (activități recreative"),
    ("G01.01", u"Sporturi nautice"),
    ("G01.01.01", u"Sporturi nautice motorizate"),
    ("G01.01.02", u"Sporturi nautice non-motorizate"),
    ("G01.02", u"Mersul pe jos,călărie și vehicule non-motorizate"),
    ("G01.03", u"Vehicule cu motor"),
    ("G01.03.01", u"Conducerea obișnuită a vehiculelor motorizate"),
    ("G01.03.02", u"Conducerea în afara drumului a vehiculelor motorizate"),
    ("G01.04", u"Drumeții montane, alpinism, speologie."),
    ("G01.04.01", u"Alpinism"),
    ("G01.04.02", u"Speologie"),
    ("G01.04.03", u"Vizite de agrement în peșteri"),
    ("G01.05", u"Planorism, delta plan, parapantă, balon."),
    ("G01.06", u"Ski în afara pârtiilor"),
    ("G01.07", u"Scubadiving, snorkeling (scufundări cu scafandru autonom sau cu (snorkel)"),
    ("G01.08", u"Alte activități sportive și recreative în aer liber"),
    ("G02", u"Complexe sportive și de odihnă"),
    ("G02.01", u"Terenuri de golf"),
    ("G02.02", u"Complex de ski"),
    ("G02.03", u"Stadion"),
    ("G02.04", u"Circuite auto"),
    ("G02.05", u"Hipodrom"),
    ("G02.06", u"Parc de distracții"),
    ("G02.07", u"Baze sportive"),
    ("G02.08", u"Locuri de campare și zone de parcare pentru rulote"),
    ("G02.09", u"Observatoare ale faunei sălbatice"),
    ("G02.10", u"Alte sporturi/complexe de agrement"),
    ("G03", u"Centre de practicare activități demonstrative"),
    ("G04", u"Utilități militare și antrenament civil (mișcări civile)"),
    ("G04.01", u"Manevre militare"),
    ("G04.02", u"Utilități militare abandonate"),
    ("G05", u"Alte intruziuni și dezechilibre umane"),
    ("G05.01", u"Tasarea, supraexploatarea"),
    ("G05.02", u"Abraziune de suprafață/deteriorare mecanică a suprafeței fundului (de mare"),
    ("G05.03", u"Penetrare/deteriorarea suprafeței fundului mării"),
    ("G05.04", u"Vandalism"),
    ("G05.05", u"Întreținerea intensivă a parcurilor publice/curățarea plajelor"),
    ("G05.06", u"Curățarea copacilor, tăierea pentru siguranța publică, (îndepărtarea de copaci pe marginea drummului"),
    ("G05.07", u"Lipsa sau îndepărtarea greșită a măsurilor de conservare"),
    ("G05.08", u"Inchiderea peșterilor sau a galeriilor"),
    ("G05.09", u"Garduri, ingrădiri"),
    ("G05.10", u"Survolarea cu aeronave(agricol)"),
    ("G05.11", u"Moartea sau rănirea prin colilziune"),
    ("H", u"Poluarea"),
    ("H01", u"Poluarea apelor de suprafață (limnice, terestre, marine și salmastre)"),
    ("H01.01", u"Poluarea apelor de suprafață de către combinate industriale"),
    ("H01.02", u"Poluarea apelor de suprafață prin inundații"),
    ("H01.03", u"Alte surse de poluare a apelor de suprafață"),
    ("H01.04", u"Poluarea difuză a apelor de suprafață prin inundații sau scurgeri (urbane"),
    ("H01.05", u"Poluarea difuză a apelor de suprafață, cauzată de activități (agricole și forestiere"),
    ("H01.06", u"Poluarea difuză a apelor de suprafață cauzată de transport și de (infrastructură fără conectare la canalizare/mașini de măturat strazi"),
    ("H01.07", u"Poluarea difuză a apelor de suprafață cauzată de platformele (industriale abandonate"),
    ("H01.08", u"Poluarea difuză a apelor de suprafață cauzată de apa de canalizare (menajera și de ape uzate"),
    ("H01.09", u"Poluarea difuză a apelor de suprafață cauzată de apa de alte surse (care nu sunt enumerate"),
    ("H02", u"Poluarea apelor subterane (surse punctiforme și difuze)"),
    ("H02.01", u"Poluarii apelor subterane cu scurgeri din zone contaminate"),
    ("H02.02", u"Poluarii apelor subterane cu scurgeri provenite din zone în care (sunt depozitate deșeuri"),
    ("H02.03", u"Poluarea apelor subterane asociată cu infrastructura din industria (de petrol"),
    ("H02.04", u"Poluarea apelor subterane prin evacuarea apelor de mina"),
    ("H02.05", u"Popluarea apelor subterane cauzată de descarcarea apei contaminate (de infiltrație"),
    ("H02.06", u"Poluarea difuza a apelor subterane cauzată de activități agricole (și forestiere"),
    ("H02.07", u"Poluarea difuza a apelor subterane cauzată de non-canalizare"),
    ("H02.08", u"Poluarea difuza a apelor subterane cauzată de terenurile urbane"),
    ("H03", u"Poluarea apei marine"),
    ("H03.01", u"Deversărilor de petrol în mare"),
    ("H03.02", u"Descărcarea de materiale toxice chimice în mare"),
    ("H03.02.01", u"Contaminare cu compuși non-sintetici"),
    ("H03.02.02", u"Contaminare cu compuși sintetici"),
    ("H03.02.03", u"Contaminare cu radionuclizi"),
    ("H03.02.04", u"Introducerea de alte substanțe (de exemplu, lichide, gaze)"),
    ("H03.03", u"Macro-poluare marină (de exemplu, pungi de plastic, polistiren)"),
    ("H04", u"Poluarea aerului, poluanți răspândiți pe calea aerului"),
    ("H04.01", u"Ploi acide"),
    ("H04.02", u"Poluare cu azot(compuși azotați)"),
    ("H04.03", u"Alte forme de poluare a aerului"),
    ("H05", u"Poluarea solului și deșeurile solide (cu excepția evacuărilor)"),
    ("H05.01", u"Gunoiul și deșeurile solide"),
    ("H06", u"Excesul de energie"),
    ("H06.01", u"Zgomot, poluare fonică"),
    ("H06.01.01", u"Poluarea fonică cauzată de o sursă neregulată"),
    ("H06.01.02", u"Poluarea fonică cauzată de o sursă difuză sau permanentă"),
    ("H06.02", u"Poluare luminoasă"),
    ("H06.03", u"Incălzire termică a corpurilor de apă"),
    ("H06.04", u"Modificări electromagnetice"),
    ("H06.05", u"Explorare seismică, explozii"),
    ("H07", u"Alte forme de poluare"),
    ("I", u"Specii invazive, alte probleme ale speciilor și genele"),
    ("I01", u"Specii invazive non-native(alogene)"),
    ("I02", u"Specii native(indigene) problematice"),
    ("I03", u"Organisme modificate genetic (OMG)"),
    ("I03.01", u"Poluare genetică(animale)"),
    ("I03.02", u"Poluare genetică(plante)"),
    ("J", u"Modificări ale sistemului natural"),
    ("J01", u"Focul și combaterea incendiilor"),
    ("J01.01", u"Incendii"),
    ("J01.02", u"Combaterea incendiilor naturale"),
    ("J01.03", u"Lipsa de incendii"),
    ("J02", u"Schimbări provocate de oameni în sistemele hidraulice (zone umede și (mediul marin)"),
    ("J02.01", u"Umplerea bazinelor acvatice cu pământ, îndiguirea și asanarea: (generalități"),
    ("J02.01.01", u"Polderizare - îndiguire în vederea creării unor incinte (agricole, silvice, piscicole etc."),
    ("J02.01.02", u"Recuperarea de terenuri din mare, estuare sau mlaștini"),
    ("J02.01.03", u"Umplerea șanțurilor,zăgazurilor,heleșteelor, iazurilor, (mlaștinilor sau gropilor"),
    ("J02.01.04", u"Recultivarea zonelor miniere"),
    ("J02.02", u"Înlăturarea de sedimente(mâl)"),
    ("J02.02.01", u"Dragare/îndepărtarea sedimentelor limnice"),
    ("J02.02.02", u"Dragare în estuare și de coastă"),
    ("J02.03", u"Canalizare și deviere de apă"),
    ("J02.03.01", u"Deviere a apei la scară mare"),
    ("J02.03.02", u"Canalizare"),
    ("J02.04", u"Modificări de inundare"),
    ("J02.04.01", u"Inundare"),
    ("J02.04.02", u"Lipsa de inundații"),
    ("J02.05", u"Modificarea funcțiilor hidrografice, generalități"),
    ("J02.05.01", u"Modificarea debitului de apă(maree și curenți marini)"),
    ("J02.05.02", u"Modificarea structurii cursurilor de apă continentale"),
    ("J02.05.03", u"Modificarea apelor stătătoare"),
    ("J02.05.04", u"Rezervoare"),
    ("J02.05.05", u"Hidrocentrale mici, stăvilare"),
    ("J02.05.06", u"Modificarea gradului de expunere la valuri"),
    ("J02.06", u"Captarea apelor de suprafață"),
    ("J02.06.01", u"Captări de apă de suprafață pentru agricultură"),
    ("J02.06.02", u"Captări de apă de suprafață pentru alimentarea cu apă"),
    ("J02.06.03", u"Captări de apă de suprafață pentru industrie"),
    ("J02.06.04", u"Captări de apă de suprafață pentru producția de energie (electrică(de racire)"),
    ("J02.06.05", u"Captări de apă de suprafață pentru fermele piscicole"),
    ("J02.06.06", u"Captări de apă de suprafață pentru hidro-centrale"),
    ("J02.06.07", u"Captări de apă de suprafață pentru cariere/deschise(cărbune)"),
    ("J02.06.08", u"Captări de apă de suprafață pentru navigare"),
    ("J02.06.09", u"Captări de apă de suprafață pentru transferul de apă"),
    ("J02.06.10", u"Alte captări importante de apă de suprafață"),
    ("J02.07", u"Captarea apelor subterane"),
    ("J02.07.01", u"Captări de apa subterană pentru agricultură"),
    ("J02.07.02", u"Captări de apa subterană pentru alimentarea publică cu apă"),
    ("J02.07.03", u"Captări de apa subterană pentru industrie"),
    ("J02.07.04", u"Captări de apa subterană pentru cariere/deschise(cărbune)"),
    ("J02.07.05", u"Alte captări importante de apă subterană pentru agricultură"),
    ("J02.08", u"Creșterea nivelului apelor subterane/recircularea artificială a (apelor subterane"),
    ("J02.08.01", u"Evacuări în apele subterane în scopuri de recirculare (artificială"),
    ("J02.08.02", u"Recircularea de apa subterană la bazinul freatic de la care a (fost extrasă"),
    ("J02.08.03", u"Recircularea apei de mină"),
    ("J02.08.04", u"Other major groundwater recharge"),
    ("J02.09.", u"Intruziune de apă sarată în pânza freatică"),
    ("J02.09.01", u"Intruziune de apă sarată"),
    ("J02.09.02", u"Alte intruziuni"),
    ("J02.10", u"Managementul vegetației acvatice și de mal în scopul drenării"),
    ("J02.11", u"Variațiile ratei de înnămolire, de descărcare, depozitarea (materialului dragat"),
    ("J02.11.01", u"Descărcarea, depozitarea materialului dragat"),
    ("J02.11.02", u"Alte modificări ale ratei de înnămolire"),
    ("J02.12", u"Stăvilare, diguri, plaje artificiale, generalități"),
    ("J02.12.01", u"Lucrări de protecție a mării sau a coastei, baraje maree"),
    ("J02.12.02", u"Diguri de apărare pentru inundații în sistemele de apă (interioare"),
    ("J02.13", u"Abandonarea gestionării cursurilor de apă"),
    ("J02.14", u"Deteriorarea calității apei din cauza modificărilor antropice de (salinitate"),
    ("J02.15", u"Alte schimbări ale condițiilor hidraulice cauzate de activități (umane"),
    ("J03", u"Alte modificări ale ecosistemelor"),
    ("J03.01", u"Reducerea sau pierderea de caracteristici specifice de habitat"),
    ("J03.01.01", u"Reducerea disponibilității de pradă (inclusiv cadavre, (rămășițe)"),
    ("J03.02", u"Reducerea conectivității de habitat, din cauze antropice"),
    ("J03.02.01", u"Reducerea migrației/bariere de migrație"),
    ("J03.02.02", u"Reducerea dispersiei"),
    ("J03.02.03", u"Reducerea schimbului genetic"),
    ("J03.03", u"Reducere, lipsa sau prevenirea eroziunii"),
    ("J03.04", u"Cercetări aplicative(industriale) distructive"),
    ("K", u"Procesele naturale biotice și abiotice(fără catastrofe)"),
    ("K01", u"Procesele naturale abiotice(lente)"),
    ("K01.01", u"Eroziune"),
    ("K01.02", u"Colmatare"),
    ("K01.03", u"Secare"),
    ("K01.04", u"Inundare"),
    ("K01.05", u"Salinizarea solului"),
    ("K02", u"Evoluție biocenotică, succesiune"),
    ("K02.01", u"Schimbarea compoziției de specii(succesiune)"),
    ("K02.02", u"Acumularea de material organic"),
    ("K02.03", u"Eutrofizare(naturală)"),
    ("K02.04", u"Acidifiere(naturală)"),
    ("K03", u"Relații interspecifice faunistice"),
    ("K03.01", u"Competiția"),
    ("K03.02", u"Parazitism"),
    ("K03.03", u"Introducere a unor boli (patogeni microbieni)"),
    ("K03.04", u"Prădătorism"),
    ("K03.05", u"Antagonism care decurge din introducerea de specii"),
    ("K03.06", u"Antagonism cu animale domestice"),
    ("K03.07", u"Alte forme de competiție interspecifică faunistică"),
    ("K04", u"Relații interspecifice ale florei"),
    ("K04.01", u"Competiție"),
    ("K04.02", u"Parazitism"),
    ("K04.03", u"Introducere a unor boli (patogeni microbieni)"),
    ("K04.04", u"Lipsa de agenți de polenizare"),
    ("K04.05", u"Daune cauzate de erbivore (inclusiv specii de vanat)"),
    ("K05", u"Fecunditate redusă/depresie genetică"),
    ("K05.01", u"Fertilitate redusă/depresie genetică la animale(consangvinizare)"),
    ("K05.02", u"Fertilitate redusă/depresie genetică la plante(inclusiv endogamia)"),
    ("K06", u"Alte forme sau forme mixte de competiție interspecifică a florei"),
    ("L", u"Evenimente geologice, catastrofe naturale"),
    ("L01", u"Activitate vulcanică"),
    ("L02", u"Valuri mareice, tsunami"),
    ("L03", u"Cutremure"),
    ("L04", u"Avalanșe"),
    ("L05", u"Prăbușiri de teren, alunecari de teren"),
    ("L06", u"Prăbușiri subterane"),
    ("L07", u"Furtuni, cicloane"),
    ("L08", u"Inundații(procese naturale)"),
    ("L09", u"Incendii(naturale)"),
    ("L10", u"Alte catastrofe naturale"),
    ("M", u"Schimbări globale"),
    ("M01", u"Schimbarea condițiilor abiotice"),
    ("M01.01", u"Schimbarea temperaturii(ex creșterea temperaturii și extremele)"),
    ("M01.02", u"Secete și precipitații reduse"),
    ("M01.03", u"Inundații si creșterea precipitațiilor"),
    ("M01.04", u"Schimbarea pH-ului"),
    ("M01.05", u"Modificări de debit(limnic, mareic, oceanic)"),
    ("M01.06", u"Modificarea valurilor"),
    ("M01.07", u"Modificarea nivelului mărilor"),
    ("M02", u"Schimbarea condițiilor biotice"),
    ("M02.01", u"Înlocuirea și deteriorarea habitatului"),
    ("M02.02", u"Desincronizarea proceselor"),
    ("M02.03", u"Declinul sau dispariția speciilor"),
    ("M02.04", u"Migrația speciilor (nou veniți, natural)"),
    ("U", u"No threats or pressures"),
    ("X", u"Unknown threat or pressure"),
    ("XE", u"Threats and pressures from outside the EU territory"),
    ("XO", u"Threats and pressures from outside the Member State"),
]
